# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeiBo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeiBo

  pod 'SDWebImage'
  pod 'YYModel'
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'SVProgressHUD'

end
